Repository cta-observatory/pyirf, pull requests merged in 2020-10, with the labels that each got.

#79 Fix integration of power law pdf in simulations.py
  pyirf/simulations.py
Labels: bug

#84 Update docs
  docs/examples.rst
Labels: documentation

#70 Doc cuts and bump version
  docs/changelog.rst
  docs/cuts.rst
  docs/index.rst
  pyirf/cuts.py
  pyirf/version.py
Labels: documentation, maintenance

#96 Add integration test
  .travis.yml
  pyirf/io/gadf.py
  pyirf/io/tests/test_gadf.py
  pyirf/tests/test_eventdisplay_comparison.py
  setup.py
Labels: maintenance
