Repository cta-observatory/pyirf, pull requests merged in 2020-09, with the labels that each got.

#12 EventDisplay comparison
  .gitignore
  .prospector.yaml
  .travis.yml
  CODEOWNERS
  MANIFEST.in
  README.rst
  docs/AUTHORS.rst
  docs/changelog.rst
  docs/conf.py
  docs/contribute/comparison_with_EventDisplay.ipynb
  docs/contribute/index.rst
  docs/contribute/repo.rst
  docs/index.rst
  docs/install/basic.rst
  docs/install/developer.rst
  docs/install/index.rst
  docs/io/index.rst
  docs/perf/index.rst
  docs/requirements.txt
  docs/resources/index.rst
  docs/scripts/index.rst
  docs/usage/EventDisplay.rst
  docs/usage/index.rst
  docs/usage/lstchain_irf.rst
  docs/usage/protopipe.rst
  environment.yml
  notebooks/comparison_with_EventDisplay.ipynb
  pyirf/__init__.py
  pyirf/io/__init__.py
  pyirf/io/io.py
  pyirf/io/tests/test_io.py
  pyirf/perf/__init__.py
  pyirf/perf/cut_optimisation.py
  pyirf/perf/irf_maker.py
  pyirf/perf/utils.py
  pyirf/resources/config.yml
  pyirf/resources/performance.yml
  pyirf/scripts/make_DL3.py
  pyirf/scripts/make_performance.py
  pyirf/version.py
  setup.py
Labels: benchmarking, documentation, enhancement, input/output, maintenance

#41 Add energy dispersion unit test
  docs/notebooks/comparison_with_EventDisplay.ipynb
  pyirf/irf/tests/test_energy_dispersion.py
Labels: maintenance

#46 Add PyPI deploy and metadata
  .travis.yml
  setup.cfg
Labels: maintenance

#52 Add sections about tests, coverage and building docs to docs
  docs/contribute.rst
Labels: documentation

#78 Change argument order in create_rad_max_hdu
  examples/calculate_eventdisplay_irfs.py
  pyirf/io/gadf.py
  pyirf/io/tests/test_gadf.py
Labels: breaking change
