Repository cta-observatory/pyirf, pull requests merged in 2021-04, with the labels that each got.

#147 Fix benchmark functions for events outside given bins
  pyirf/benchmarks/angular_resolution.py
  pyirf/benchmarks/energy_bias_resolution.py
  pyirf/benchmarks/tests/test_angular_resolution.py
  pyirf/benchmarks/tests/test_bias_resolution.py
Labels: benchmarking, fix

#145 Proton+Helium spectrum from DAMPE 2019 ICRC proceeding
  MANIFEST.in
  docs/examples.rst
  examples/plot_spectra.py
  pyirf/resources/dampe_p+he.ecsv
  pyirf/spectral.py
  pyirf/tests/test_spectral.py
  setup.py
Labels: enhancement

#144 Add function to compute bias and resolution from energy dispersion
  pyirf/benchmarks/__init__.py
  pyirf/benchmarks/energy_bias_resolution.py
  pyirf/benchmarks/tests/test_bias_resolution.py
Labels: benchmarking, enhancement

#141 Interpolate irfs
  pyirf/binning.py
  pyirf/cuts.py
  pyirf/interpolation.py
  pyirf/io/gadf.py
  pyirf/tests/test_binning.py
  pyirf/tests/test_cuts.py
  pyirf/tests/test_interpolation.py
Labels: enhancement, input/output
