Repository cta-observatory/pyirf, pull requests merged in 2023-09, with the labels that each got.

#256 Add estimate_background to __all__
  pyirf/sensitivity.py
Labels: documentation, no-changelog-needed

#254 Fix leftover config errors after renaming default branch to main
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  docs/index.rst
Labels: no-changelog-needed

#255 Extend and rework IRF interpolation docs
  docs/interpolation.rst
  pyirf/interpolation/base_extrapolators.py
  pyirf/interpolation/component_estimators.py
  pyirf/interpolation/griddata_interpolator.py
  pyirf/interpolation/moment_morph_interpolator.py
  pyirf/interpolation/nearest_neighbor_searcher.py
  pyirf/interpolation/nearest_simplex_extrapolator.py
  pyirf/interpolation/quantile_interpolator.py
  pyirf/interpolation/utils.py
Labels: documentation, IRF interpolation, no-changelog-needed

#262 Render changelog for 0.10.1
  CHANGES.rst
  docs/changes/258.bugfix.rst
Labels: no-changelog-needed
