Repository cta-observatory/pyirf, pull requests merged in 2023-07, with the labels that each got.

#232 Add Nearest Neighbor Searcher as Alternative for Inter-/Extrapolation
  docs/changes/232.feature.rst
  pyirf/interpolation/__init__.py
  pyirf/interpolation/base_interpolators.py
  pyirf/interpolation/component_estimators.py
  pyirf/interpolation/nearest_neighbor_searcher.py
  pyirf/interpolation/tests/test_base_interpolators.py
  pyirf/interpolation/tests/test_component_estimator_base_classes.py
  pyirf/interpolation/tests/test_nearest_neighbor_searcher.py
Labels: IRF interpolation

#233 Use importlib resources instead of deprecated pkg_resources
  pyirf/spectral.py
  setup.py
Labels: maintenance, no-changelog-needed

#235 Correct GridDataInterpolator Testfile
  pyirf/interpolation/tests/test_griddata_interpolator.py
Labels: no-changelog-needed

#242 Update .github workflows
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
Labels: maintenance, no-changelog-needed

#243 Update python to >= 3.9
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .readthedocs.yml
  docs/changes/243.maintenance.rst
  environment.yml
  pyirf/spectral.py
  setup.cfg
  setup.py
Labels: maintenance

#244 Update author_email
  setup.cfg
Labels: maintenance, no-changelog-needed

#237 MomentMorphNearestSimplexExtrapolator for Discretized PDF Components
  docs/changes/237.feature.rst
  pyirf/interpolation/__init__.py
  pyirf/interpolation/moment_morph_interpolator.py
  pyirf/interpolation/nearest_simplex_extrapolator.py
  pyirf/interpolation/tests/test_nearest_simplex_extrapolator.py
Labels: IRF interpolation

#245 Have ComponentEstimators sort input in increasing order for 1D-grids
  pyirf/interpolation/component_estimators.py
  pyirf/interpolation/tests/test_component_estimator_base_classes.py
Labels: IRF interpolation, no-changelog-needed

#246 Render changelog for 0.9
  .readthedocs.yml
  CHANGES.rst
  CODEOWNERS
  docs/changes/228.api.rst
  docs/changes/229.feature.rst
  docs/changes/231.bugfix.rst
  docs/changes/232.feature.rst
  docs/changes/236.feature.rst
  docs/changes/237.feature.rst
  docs/changes/240.bugfix.rst
  docs/changes/241.bugfix.rst
  docs/changes/243.maintenance.rst
Labels: documentation, no-changelog-needed

#248 master -> main
  .github/workflows/release-drafter.yml
  README.rst
Labels: maintenance, no-changelog-needed
